### ISSUE TITLE
test dyn-bathe not working

### ISSUE THREAD

**Issue by RaulDurand** [NumSoftware/Amaru#11] opened 2018-05-19 09:59 UTC
After last pull request from @bgpantojar test dyn-bathe.jl is still not working. The dynsolver shows the SingularException message. Could it be a problem when the pull request was merged?
I suggest to update the locar repository (git pull) to get the last changes in master:   
  ro->rho  and  auto_inc -> autoinc

**Comment by bgpantojar** [comment] 2018-05-19 13:29
In the version that I worked this test was already working (posibly because I used the version of Amaru disponible in febrary). After use the current version I realized of the same problem. I tested it without reinforce and the code working well. I think that the problem is in the files of the rod and interface elements. I will be looking for a solution. I think too that probably the problem was in the moment of merged.

**Comment by bgpantojar** [comment] 2018-05-19 13:54
I reviewed the files that I made pull request and found that the files mech-rod.jl and elastic-rod.jl actually were not updated.

**Comment by bgpantojar** [comment] 2018-05-19 14:32
I already updated the file mech-rod.jl. Now it is working well.

**Comment by RaulDurand** [comment] 2018-05-20 01:33
Nice job! It is working now.

**Comment by RaulDurand** [comment] 2018-05-20 19:54
Line 338 in dyn-solver.jl currently shows:
        Fex_Fin = Fex-Fin
Should it be 
        Fex_Fin = Fex-Fina    ?
Please check if there are other merge problems in this file.

**Comment by bgpantojar** [comment] 2018-05-20 20:41
Actually the Line 338 in dyn-solver.jl is: Fex_Fin = Fex-Fina. Despite that, this line was not affecting the solution. In a new pull request was solved that.

**Closed** 2018-05-20 21:41 UTC
